---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: k8s
  labels:
    app: demo_k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo_k8s
      tier: database
  template:
    metadata:
      namespace: k8s
      name: database
      labels:
        app: demo_k8s
        tier: database
    spec:
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: database-pvc
      containers:
          # ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: congntss
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: database-volume
              mountPath: /var/lib/mysql
