---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
  namespace: demo-k8s
  labels:
    app: demo_k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo_k8s
      tier: rails
  template:
    metadata:
      name: rails
      labels:
        app: demo_k8s
        tier: rails
    spec:
      containers:
        - name: rails
          image: congttl/rails_app
          command: ["bin/rails"]
          args: ["s", "-p", "3000", "-b", "0.0.0.0"]
          envFrom:
            - secretRef:
                name: secret-env
            - configMapRef:
                name: configmap-env
