apiVersion: v1
kind: Pod
metadata:
  name: compose
  labels:
    app: app3
    ungdung: ungdung3
spec:
  containers:
  - name: nginx
    image: nginx:1.17.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80

  - name: node
    image: congttl/docs:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 3000