---
  - hosts: node_master
    remote_user: k8s
    become: yes
    vars:
      - ip_address: 188.166.252.80
      - working_dir: /home/k8s
      - group: k8s
      - owner: k8s
    tasks:
      - name: initialize the cluster
        shell: kubeadm init --apiserver-advertise-address={{ ip_address }} --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
        args:
          chdir: $HOME
          creates: cluster_initialized.txt

      - name: create .kube directory
        file:
          path: $HOME/.kube
          state: directory
          mode: 0755

      - name: copy admin.conf to user's kube config
        copy:
          src: /etc/kubernetes/admin.conf
          dest: "{{working_dir}}/.kube/config"
          remote_src: yes
          owner: "{{ owner }}"

      - name: install Pod network
        shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
        args:
          chdir: $HOME
          creates: pod_network_setup.txt