---
  - hosts: node_master
    remote_user: k8s
    become: yes
    vars:
      - ip_address: 188.166.252.80
      - working_dir: /home/k8s
      - group: k8s
      - owner: k8s
    tasks:
      - name: edit file /etc/hosts
        blockinfile:
          dest: /etc/hosts
          insertbefore: BOF
          block: |
            188.166.252.80 master.xtl
            128.199.180.44 worker1.xtl

      - name: initialize the cluster
        shell: kubeadm init --apiserver-advertise-address={{ ip_address }} --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
        args:
          chdir: "{{ working_dir }}"
          creates: cluster_initialized.txt

      - name: create .kube directory
        file:
          path: "{{working_dir}}/.kube"
          state: directory
          mode: 0755

      - name: copy admin.conf to user's kube config
        copy:
          src: /etc/kubernetes/admin.conf
          dest: "{{working_dir}}/.kube/config"
          remote_src: yes
          owner: "{{ owner }}"

      - name: install Pod network
        shell: kubectl apply -f https://docs.projectcalico.org/v3.10/manifests/calico.yaml >> pod_network_setup.txt
        args:
          chdir: "{{ working_dir }}"
          creates: pod_network_setup.txt