---
  - hosts: node_master
    remote_user: k8s
    become: yes
    vars:
      - ip_address: 188.166.252.80
      - working_dir: /home/k8s
      - group: k8s
      - owner: k8s
    roles:
      - initialize-cluster