apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment
spec:
  maxReplicas: 10
  minReplicas: 9
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment
  targetCPUUtilizationPercentage: 80