apiVersion: v1
kind: Pod
metadata:
  namespace: ingress
  name: app
  labels:
    name: app
spec:
  containers:
    - name: app
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
      resources: {}