apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
  - name: documents
    image: congttl/docs:latest
    resources:
      limits:
        memory: "150M"
        cpu: "100m"
    ports:
      - containerPort: 3000