apiVersion: v1
kind: ReplicationController
metadata:
  name: replicaapp
spec:
  replicas: 3
  # chon POD có label là app
  selector:
    app: app
  # template mà POD nó đang chạy
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
      - name: documents
        image: congttl/docs:latest
        resources:
          limits:
            memory: "150M"
            cpu: "100m"
        ports:
          - containerPort: 3000