---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: demo-k8s
  labels:
    app: db-service
spec:
  type: ClusterIP
  selector:
    app: app_rails
    tiger: database
  ports:
    - port: 3306
      targetPort: 3306