---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: demo-k8s
  labels:
    app: demo_k8s
    tier: database
spec:
  selector:
    app: demo_k8s
    tier: database
  ports:
    - port: 3306