---
apiVersion: v1
kind: Service
metadata:
  name: rails
  namespace: demo-k8s
  labels:
    app: demo_k8s
    tier: rails
spec:
  type: NodePort
  selector:
    app: demo_k8s
    tiger: rails
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001