---
apiVersion: v1
kind: Service
metadata:
  name: rails
  namespace: k8s
  labels:
    app: demo_k8s
spec:
  type: NodePort
  selector:
    app: demo_k8s
    tier: rails
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001

  # type: LoadBalancer
  # selector:
  #   app: demo_k8s
  #   tier: rails
  # ports:
  # - port: 80
  #   targetPort: 3000