---
apiVersion: v1
kind: Service
metadata:
  name: rails
  
  labels:
    app: demo_k8s
spec:
  type: NodePort
  selector:
    app: demo_k8s
    tier: rails
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
