apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  volumes:
  - name: cert-volume
    secret:
      secretName: "nginx-cert"
  containers:
  - name: nginx
    image: congttl/kube:nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
      - containerPort: 433
    volumeMounts:
      - mountPath: "/certs"
        name: cert-volume