apiVersion: v1
kind: Pod
metadata:
  name: ungdungnode
  label:
    app: app1
    ungdung: ungdung1
spec:
  containers:
  - name: c1
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "150M"
        cpu: "100m"
    ports:
      - containerPort: 8085