apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: app2
    ungdung: ungdung2
spec:
  containers:
    - name: n1
      image: nginx:1.17.6
      resources:
        limits:
          memory: "128Mi"
          cpu: "150m"
      ports:
        - containerPort: 80