---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-env
  namespace: k8s
  labels:
    app: demo_k8s
    tier: env
data:
  APP: configmap_k8s
  RAILS_ENV: production
  REDIS_URL: redis
  REDIS_PORT: "6379"