---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-pv
  namespace: k8s
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-pvc
  namespace: k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
