---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: db-daemonset
  namespace: demo-k8s
spec:
  selector:
    matchLabels:
      app: app_rails
      tiger: database
  template:
    metadata:
      name: database 
      labels:
        app: app_rails
        tiger: database
    spec:
      volumes:
        - name: db-data
          hostPath: 
            path: /db_data
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: congnt
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql