---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: database
  labels:
    app: demo_k8s
spec:
  selector:
    matchLabels:
      app: demo_k8s
      tier: database
  template:
    metadata:
      name: database
      labels:
        app: demo_k8s
        tier: database
    spec:
      volumes:
        - name: db-data
          hostPath:
            path: /db_data
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: congnt
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
