---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: demo-k8s
  name: pv-mysql
spec:
  storageClassName: mysql-volume
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/v1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demo-k8s
  name: pvc-mysql
spec:
  storageClassName: mysql-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi