---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-setup
  namespace: demo-k8s
spec:
  backoffLimit: 1
  template:
    metadata:
      name: setup
    spec:
      restartPolicy: "Never"
      containers:
        - name: setup
          image: congttl/rails_app
          command: ["bin/rails"]
          args: ["db:create", "db:migrate", "db:seed"]
          envFrom:
            - secretRef:
                name: secret-env
            - configMapRef:
                name: configmap-env