---
apiVersion: v1
kind: Secret
metadata:
  name: secret_env
  namespace: demo-k8s
  labels:
    app: app_rails
    tiger: secret
data:
  DATABASE_USER: root
  DATABASE_PASSWORD: password
  DATABASE_HOSTNAME: "127.0.0.1"
  DATABASE_NAME: k8s_production
