---
apiVersion: v1
kind: Secret
metadata:
  name: secret-env
  namespace: demo-k8s
  labels:
    app: app_rails
    tiger: secret
data:
  DATABASE_USER: cm9vdA==
  DATABASE_PASSWORD: cGFzc3dvcmQ=
  DATABASE_HOSTNAME: MTI3LjAuMC4x
  DATABASE_NAME: azhzX3Byb2R1Y3Rpb24=
