apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 3000
      nodePort: 30001
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30002
  selector:
    app: app