---
#
# THAM KHAO https://cuongquach.com/cai-dat-kubernetes-cluster-voi-kubeadm.html
# THAM KHAO https://www.digitalocean.com/community/tutorials/how-to-create-a-kubernetes-cluster-using-kubeadm-on-ubuntu-18-04
#

- name: copy file k8s.config interaction with bridge
  copy: src=files/k8s.conf dest=/etc/sysctl.d

- name: install a few prerequisite packages
  apt: name={{ item }} state=present
  with_items:
    - ebtables
    - ethtool
    - apt-transport-https
    - curl

- name: add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add Kubernetes APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'

- name: upgrade all packages to the latest version
  apt: name="*" state=latest

- name: install kubelet kubeadm kubectl
  apt: name={{ item }} state=present
  with_items:
    - kubelet
    - kubelet
    - kubeadm

- name: hold kubelet kubeadm kubectl
  command: apt-mark hold kubelet kubeadm kubectl