
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sidekiq
  namespace: k8s
spec:
  selector:
    matchLabels:
      app: demo_k8s
      tier: sidekiq
  template:
    metadata:
      name: sidekiq
      labels:
        app: demo_k8s
        tier: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: congttl/rails_app
        command: ["bundle"]
        args: ["exec", "sidekiq"]
        envFrom:
          - secretRef:
              name: secret-env
          - configMapRef:
              name: configmap-env
